### ISSUE TITLE
Username/Password authentication not working

### ISSUE THREAD

**Issue by Chiyo-no-sake** [solid-contrib/solid-node-client#18]
Steps required to recreate:
- Create an account on solidcommunity.net
- run a node script/server that executes the login as shown in the README.md of the repository:
```
    this.client = new SolidNodeClient()
    await this.client.login({
      idp: SOLID_IDP,
      username: SOLID_USERNAME,
      password: SOLID_PASSWORD,
    })
```

Expected behavior: Login request to the server (and successful authentication)
Actual behavior: The library throws an exception from solid authn:

```
Uncaught ConfigurationError Error: OidcLoginHandler requires an OIDC issuer: missing property 'oidcIssuer' in {"sessionId":"6136962f-6922-47f4-ada6-c2d46bbb23a4","tokenType":"DPoP","eventEmitter":{"_events":{},"_eventsCount":3,"tokenRequestInProgress":false,"lastTimeoutHandle":0,"clientAuthentication":{"loginHandler":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"oidcHandler":{"handleables":[{"tokenRefresher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"issuerConfigFetcher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"clientRegistrar":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}},"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},{"tokenRefresher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"issuerConfigFetcher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"clientRegistrar":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}},"_storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"redirector":{}}]},"issuerConfigFetcher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"clientRegistrar":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}},"redirectHandler":{"handleables":[{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"sessionInfoManager":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"issuerConfigFetcher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"clientRegistrar":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"tokenRefresher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}},"issuerConfigFetcher":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}},"clientRegistrar":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}}},{}]},"logoutHandler":{"sessionInfoManager":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}},"sessionInfoManager":{"storageUtility":{"secureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}},"insecureStorage":{"map":{"solidClientAuthn:registeredSessions":"[\"6136962f-6922-47f4-ada6-c2d46bbb23a4\"]"}}}}},"info":{"sessionId":"6136962f-6922-47f4-ada6-c2d46bbb23a4","isLoggedIn":false}}}
    at ConfigurationError (/home/luca/repos/mcg-api/node_modules/@inrupt/solid-client-authn-core/dist/errors/ConfigurationError.js:5:9)
    at handle (/home/luca/repos/mcg-api/node_modules/@inrupt/solid-client-authn-node/dist/login/oidc/OidcLoginHandler.js:20:19)
    at ClientAuthentication.login (/home/luca/repos/mcg-api/node_modules/@inrupt/solid-client-authn-node/dist/ClientAuthentication.js:13:57)
    at processTicksAndRejections (internal/process/task_queues:96:5)

```

**Comment by Chiyo-no-sake** [comment]
Found out it was not  your library problem
